# Generated by Django 4.1.2 on 2022-11-06 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='total',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
