# Generated by Django 4.1.2 on 2022-11-06 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_attendance_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='period',
        ),
    ]
