# Generated by Django 4.1.2 on 2022-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_attendance_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='absent',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
