# Generated by Django 4.1.2 on 2022-11-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_record_absent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='entry_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(check=models.Q(('absent', False), models.Q(('absent', True), ('entry_time__isnull', True), ('exit_time__isnull', True)), _connector='OR'), name='absent_check'),
        ),
    ]
