# Generated by Django 4.1.2 on 2022-11-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_record_entry_time_record_absent_check'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='absent_check',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('absent', False), ('entry_time__isnull', False)), models.Q(('absent', True), ('entry_time__isnull', True), ('exit_time__isnull', True)), _connector='OR'), name='absent_check'),
        ),
    ]
