# Generated by Django 4.1.2 on 2022-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_record_absent_check_record_absent_check'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='check_exit_time',
        ),
        migrations.RemoveConstraint(
            model_name='record',
            name='absent_check',
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('absent', True), ('entry_time__isnull', True), ('exit_time__isnull', True)), models.Q(('absent', False), ('entry_time__isnull', False), models.Q(('exit_time__isnull', True), ('exit_time__gt', models.F('entry_time')), _connector='OR')), _connector='OR'), name='check_time'),
        ),
    ]
