# Generated by Django 4.1.2 on 2022-11-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_record_check_exit_time_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='record',
            name='check_time',
        ),
        migrations.AlterField(
            model_name='record',
            name='entry_time',
            field=models.TimeField(),
        ),
        migrations.AddConstraint(
            model_name='record',
            constraint=models.CheckConstraint(check=models.Q(('exit_time__isnull', True), ('exit_time__gt', models.F('entry_time')), _connector='OR'), name='check_exit_time'),
        ),
    ]
